services:
  redis:
    image: redis
    ports:
      - 6379:6379

  otscapitaldj:
    image: otscapitaldj
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    ports:
      - 8000:8000
