services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=otscapitaldj
    ports:
      - 5432:5432
    volumes:
      - postgres-data1:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  otscapitaldj:
    image: otscapitaldj
    container_name: otscapitaldj
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/otscapitaldj
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RUN_MIGRATE=True
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000

volumes:
  postgres-data1: